In [1]:
import numpy as np


In [2]:
nparray=np.random.randint(1,100,size=(10,3))
print(nparray)

[[55 86 21]
 [88 96 52]
 [54 78 28]
 [99 75 86]
 [48 60  9]
 [19  7 73]
 [58 96 59]
 [29 44 49]
 [64 18 42]
 [16 82 73]]
