In [1]:
import numpy as np
arr=np.random.randint(0,100,size=(10,3))
print(arr)

[[ 1 13 68]
 [63 77 52]
 [50 74 86]
 [63  9  4]
 [ 0 21 17]
 [78 68 34]
 [95 77 53]
 [94 55 63]
 [87 72 88]
 [57 90 14]]
